# Project configuration parameters
# Items must follow format <item: subitem> OR <item:>
# Comment/Uncomment to activate/deactivate items.
datastore: 
  omop:
    server: edw.shands.ufl.edu
    database: DWS_OMOP 
  mtd:
    server: edw.shands.ufl.edu
    database: DWS_METADATA
date_range:
  start_date: 01/01/2012
  end_date: 12/31/2020
load:
  person:
  death:
  condition_occurrence:
  procedure_occurrence:
    icd: ICD coded procedures
    cpt: CPT coded procedures
  drug_exposure: 
    order: Medication orders
    admin: Medication administration
  measurement: 
    bp: Arterial blood presure
    heart_rate: Heart rate
    height: Height
    lab: Laboratory results
    pain: Pain scale
    qtcb: Q-T interval corrected Bazett
    res_dev: Respiratory device
    res_etco2: Carbon dioxide [Partial pressure] in Exhaled gas at end expiration
    res_fio2: Inhaled oxygen concentration
    res_gcs: Glasgow coma score total
    res_o2: Inhaled oxygen flow rate
    res_peep: PEEP Respiratory system
    res_pip: Peak inspiratory pressure
    res_resp: Breath rate spontaneous, mechanical, and respiratory rate
    res_spo2: Oxygen saturation in arterial blood by pulse oximetry
    res_tidal: Tidal volume setting and volume.exhaled maximum ventilator alarm
    res_vent: Ventilation mode 
    rothman: Rothman index calculated
    sofa: Sequential organ failure assessment score
    temp: Body temperature
    weight: Body weight
  observation:
    icu: Intensive care unit stay
    lda: LDA intubation type and LDA intubation start and end times
    vent: Dependence on respirator
    payer: Healthcare payer
    smoking: Tobacco smoking behavior 
    zipcode: Patient postal code
  visit_occurrence:
  provider:
  care_site:
  location:
