# Project configuration parameters
# Items must follow format <item: subitem> OR <item:>
release_info:
  output_path: '//share.ahc.ufl.edu/share$/DSS/IDR_Projects/COVID-19/OMOP/data_releases/' 
  version: 'v7'

date_range:
  start_date: 01/01/2012
  end_date: 12/31/2020

bo_docs:
  cohort: "cohort_COVID_Broad"
  stage: "omop"

load:
# Comment line to ignore data elements under each omop table with sub-items.
# Note: Do not comment tables. At least one sub-item must be active.
  person:
  death:
  visit_occurrence:
  condition_occurrence:
  procedure_occurrence:
    icd: ICD coded procedures
    cpt: CPT coded procedures
  drug_exposure: 
    order: Medication orders
    admin: Medication administration
  measurement: 
    bp: Blood pressure 
    bp_artline: Invasive blood pressure
    bp_noninvasive: Non-invasive blood presure
    bp_cvp: 
    bp_cvp_mean: 
    bp_map_artline: Mean arterial pressure invasive methods
    bp_map_cuff: Mean arterial pressure manual (Cuff)
    bp_map_noninvasive: Mean arterial pressure non-invasive methods
    bp_pap_mean: Pulmonary Artery Pressure
    heart_rate: Heart rate
    height: Height
    lab: Laboratory results
    pain: Pain scale
    pain_jax: 
    pain_peds: 
    qtcb: Q-T interval corrected Bazett
    res_dev: Respiratory device
    res_etco2: Carbon dioxide [Partial pressure] in Exhaled gas at end expiration
    res_fio2: Inhaled oxygen concentration
    res_gcs: Glasgow coma score total
    res_gcs_peds: 
    res_o2: Inhaled oxygen flow rate
    res_o2_ml: 
    res_peep: PEEP Respiratory system
    res_pip: Peak inspiratory pressure
    res_resp: Breath rate spontaneous, mechanical, and respiratory rate
    res_resp_adultmech: 
    res_resp_adultspont: 
    res_resp_pedsmech: 
    res_resp_pedsspont: 
    res_spo2: Oxygen saturation in arterial blood by pulse oximetry
    res_tidal: Tidal volume setting 
    res_tidal_exhaled: Volume exhaled maximum ventilator alarm
    res_vent: Ventilation mode adults
    res_vent_peds: Ventilation mode pediatric
    rothman: Rothman index calculated
    sofa: Sequential organ failure assessment score
    temp: Body temperature
    weight: Body weight
  observation:
    icu: Intensive care unit stay
    lda: LDA intubation type and LDA intubation start and end times
    vent: Dependence on respirator
    payer: Healthcare payer
    smoking: Tobacco smoking behavior 
    zipcode: Patient postal code
  provider:
  care_site:
  location:

db_connections: 
  omop:
    server: edw.shands.ufl.edu
    database: DWS_OMOP 
  bo_metadata:
    server: edw.shands.ufl.edu
    database: DWS_METADATA
