image: python:3.7-alpine

pages:
  script:
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - sphinx-build -d _build/doctrees docs/source _build/html
  - mv _build/html public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  artifacts:
    paths:
    - public
  only:
  - add_docu
